version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: prod_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: coffe_crafter
    networks:
      - coffe_crafter.network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:latest
    container_name: prod_redis
    networks:
      - coffe_crafter.network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "6379:6379"

  app:
    build: .
    image: coffe_crafter.web-server:latest
    container_name: coffe_crafter.web-server
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - coffe_crafter.network
    ports:
      - "8080:8080"

  migrate:
    image: migrate/migrate
    container_name: migrate
    depends_on:
      db:
        condition: service_healthy
    entrypoint: [
      "sh", "-c",
      "migrate -path /migrations -database 'postgres://postgres:admin@db:5432/coffe_crafter?sslmode=disable' up"
    ]
    volumes:
      - ./migrations:/migrations
    networks:
      - coffe_crafter.network

networks:
  coffe_crafter.network:
    driver: bridge